#!/bin/bash

currentDate=$(date +%s)
mysqldump --defaults-extra-file="/home/admin/mysqlBackuper/cred"  --single-transaction --quick --lock-tables=false myDatabaseName | gzip > "/home/admin/mysqlBackuper/dumps/${currentDate}"

fileNames=(/home/admindb/backup/dumps/*)
countFile=${#fileNames[@]}

for ((i=countFile - 1,j=0;i>=0;i--,j++)); do
   if [[ $j -gt 4 ]]
   then
        rm "${fileNames[$i]}"
   fi
done
