#!/bin/bash

currentDate=$(date +%s)
LOCATION="/home/ypti/backup/mysqlBackuper"
mysqldump --defaults-extra-file="$LOCATION/cred"  --single-transaction --quick --lock-tables=false  ypti_dcs_dev_db_2  | xz -c > "$LOCATION/dumps/${currentDate}"

fileNames=($LOCATION/dumps/*)
countFile=${#fileNames[@]}

for ((i=countFile - 1,j=0;i>=0;i--,j++)); do
   if [[ $j -gt 4 ]]
   then
        rm "${fileNames[$i]}"
   fi
done
